# Generated by Django 5.2.5 on 2025-08-12 02:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('user_ban', 'User Ban'), ('user_unban', 'User Unban'), ('post_remove', 'Post Remove'), ('verification_approve', 'Verification Approve'), ('verification_reject', 'Verification Reject')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
