# Generated by Django 5.2.5 on 2025-08-12 02:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scam_type', models.CharField(choices=[('fake_profile', 'Fake Profile'), ('financial_scam', 'Financial Scam'), ('phishing', 'Phishing'), ('romance_scam', 'Romance Scam'), ('investment_scam', 'Investment Scam'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
