# Generated by Django 5.2.5 on 2025-08-12 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scam_detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='reported_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scam_reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scam_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
