# Generated by Django 5.2.5 on 2025-08-12 02:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrustAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('post_like', 'Post Like'), ('post_share', 'Post Share'), ('comment', 'Comment'), ('follow', 'Follow'), ('verification', 'Verification'), ('report_resolved', 'Report Resolved'), ('report_false', 'False Report'), ('spam_detected', 'Spam Detected'), ('scam_detected', 'Scam Detected')], max_length=20)),
                ('score_change', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('verified_email', 'Verified Email'), ('verified_phone', 'Verified Phone'), ('verified_id', 'Verified ID'), ('trusted_member', 'Trusted Member'), ('community_leader', 'Community Leader'), ('content_creator', 'Content Creator')], max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_score', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('verification_bonus', models.FloatField(default=0.0)),
                ('activity_score', models.FloatField(default=0.0)),
                ('community_score', models.FloatField(default=0.0)),
                ('penalty_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('fake_profile', 'Fake Profile'), ('inappropriate', 'Inappropriate Content'), ('scam', 'Scam'), ('other', 'Other')], max_length=25)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
